openapi: 3.0.0
info:
  title: Test API
  version: "1.0"
paths:
  /hello:
    get:
      summary: Say Hello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                success:
                  value:
                    message: "Hello, world!"
